name: Build and Publish Flutter Docker Image

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  docker_builder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - DOCKER_TAG: latest
            FLUTTER_VERSION: 3.29.2
          - DOCKER_TAG: stable
            FLUTTER_VERSION: 3.29.2

    env:
      BASE_IMAGE: ghcr.io/meyeroppelt/android-base
      FINAL_IMAGE: ghcr.io/meyeroppelt/flutter

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ----- Build Base Image with Cache -----
      - name: Cache Docker base layer
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-base
          key: ${{ runner.os }}-android-base
          restore-keys: |
            ${{ runner.os }}-android-base

      - name: Build and Push Base Image (if needed)
        uses: docker/build-push-action@v5
        with:
          context: ./sdk/base
          file: ./sdk/base/Dockerfile
          tags: ${{ env.BASE_IMAGE }}:latest
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache-base
          cache-to: type=local,dest=/tmp/.buildx-cache-base

      # ----- Build Flutter Layer (No cache) -----
      - name: Build and Push Flutter Layer
        uses: docker/build-push-action@v5
        with:
          context: ./sdk/flutter
          file: ./sdk/flutter/Dockerfile
          build-args: |
            flutter_version=${{ matrix.FLUTTER_VERSION }}
            BASE_IMAGE=ghcr.io/meyeroppelt/android-base:latest
          tags: |
            ${{ env.FINAL_IMAGE }}:${{ matrix.FLUTTER_VERSION }}
            ${{ env.FINAL_IMAGE }}:${{ matrix.DOCKER_TAG }}
          push: true
