name: Build and Publish Flutter Docker Image

on:
  push:
    branches: [master, main]
  workflow_dispatch:

jobs:
  docker_builder:
    runs-on: ubuntu-latest
    env:
      BASE_IMAGE: ghcr.io/meyeroppelt/android-base
      FINAL_IMAGE: ghcr.io/meyeroppelt/flutter

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read Flutter version from file
        id: get_version
        run: echo "version=$(cat scripts/flutter_version)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker base layer
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-base
          key: ${{ runner.os }}-android-base
          restore-keys: |
            ${{ runner.os }}-android-base

      - name: Build and Push Base Image
        uses: docker/build-push-action@v5
        with:
          context: ./sdk/base
          file: ./sdk/base/Dockerfile
          tags: ${{ env.BASE_IMAGE }}:latest
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache-base
          cache-to: type=local,dest=/tmp/.buildx-cache-base

      - name: Build and Push Flutter Image
        uses: docker/build-push-action@v5
        with:
          context: ./sdk/flutter
          file: ./sdk/flutter/Dockerfile
          build-args: |
            flutter_version=${{ steps.get_version.outputs.version }}
            BASE_IMAGE=${{ env.BASE_IMAGE }}:latest
          tags: |
            ${{ env.FINAL_IMAGE }}:${{ steps.get_version.outputs.version }}
            ${{ env.FINAL_IMAGE }}:latest
            ${{ env.FINAL_IMAGE }}:stable
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache-base
